CREATE TYPE "app"."event_name" AS ENUM('lead.created', 'lead.duplicate_detected', 'lead.import_completed', 'contact.created', 'contact.merged', 'contact.became_client', 'consent.updated', 'opportunity.created', 'opportunity.stage_changed', 'opportunity.won', 'opportunity.lost', 'opportunity.value_changed', 'opportunity.reopened', 'opportunity.went_cold', 'opportunity.recycled', 'call.initiated', 'call.completed', 'call.enriched', 'message.sent', 'message.received', 'message.delivery_failed', 'appointment.scheduled', 'appointment.rescheduled', 'appointment.canceled', 'appointment.completed', 'appointment.no_showed', 'calendar.sync_failed', 'activity.created', 'activity.completed', 'activity.overdue', 'sequence.enrolled', 'sequence.paused', 'sequence.completed', 'automation.executed', 'earnings.updated', 'leaderboard.rank_changed', 'celebration.triggered', 'pipeline.stage_config_changed', 'admin.setting_changed', 'user.deactivated', 'lead.reposted', 'compliance.send_blocked', 'compliance.override_started', 'compliance.override_ended', 'appointment.starting_soon', 'opportunity.gate_blocked', 'contact.owner_changed', 'contact.bad_number_flagged', 'integration.mapping_verified');--> statement-breakpoint
CREATE TYPE "app"."outbox_status" AS ENUM('pending', 'claimed', 'delivered', 'dead');--> statement-breakpoint
CREATE TYPE "app"."retention_class" AS ENUM('permanent', 'archivable');--> statement-breakpoint
CREATE TABLE "app"."event_consumer" (
	"consumer_name" text NOT NULL,
	"event_name" "app"."event_name" NOT NULL,
	CONSTRAINT "event_consumer_consumer_name_event_name_pk" PRIMARY KEY("consumer_name","event_name")
);

--> statement-breakpoint

INSERT INTO security.table_registry
  (schema_name, table_name, policy_class, owner_column, immutable, app_can_insert,
   protected_columns, exception_reason, registered_in_migration)
VALUES
  ('app', 'event_consumer', 'reference', NULL, false, false, NULL,
   'The subscription registry: which consumer listens to which of the 49 canonical events. No tenant dimension, because who listens to what is a property of the system and not of an agency. Writable only by migration -- the outbox carries a foreign key here, so a fan-out row for a consumer that does not exist cannot be written.',
   '0042_event_vocabulary')
ON CONFLICT (schema_name, table_name) DO UPDATE
  SET policy_class = EXCLUDED.policy_class, exception_reason = EXCLUDED.exception_reason;
--> statement-breakpoint

-- SEEDED FROM contracts/events/catalog.json, which is the same file that
-- generates the TypeScript union and the enum above. 268 pairs across
-- 49 events.
--
-- This is what turns the catalog's `consumers` column from documentation into a
-- constraint. Until now a module could quietly stop consuming an event and
-- nothing would notice; with the outbox keyed here, a consumer that is not
-- registered cannot receive a fan-out row at all, and
-- tests/integration/event-vocabulary.test.ts fails if the table and the
-- registry drift in either direction.
INSERT INTO app.event_consumer (consumer_name, event_name) VALUES
  ('activities', 'appointment.canceled'),
  ('activities', 'appointment.completed'),
  ('activities', 'appointment.no_showed'),
  ('activities', 'appointment.rescheduled'),
  ('activities', 'appointment.scheduled'),
  ('activities', 'call.completed'),
  ('activities', 'call.enriched'),
  ('activities', 'call.initiated'),
  ('activities', 'contact.became_client'),
  ('activities', 'contact.merged'),
  ('activities', 'lead.created'),
  ('activities', 'message.delivery_failed'),
  ('activities', 'message.received'),
  ('activities', 'message.sent'),
  ('activities', 'opportunity.created'),
  ('activities', 'opportunity.lost'),
  ('activities', 'opportunity.recycled'),
  ('activities', 'opportunity.reopened'),
  ('activities', 'opportunity.stage_changed'),
  ('activities', 'opportunity.went_cold'),
  ('activities', 'opportunity.won'),
  ('activities', 'sequence.completed'),
  ('activities', 'sequence.enrolled'),
  ('admin', 'automation.executed'),
  ('admin', 'calendar.sync_failed'),
  ('admin', 'compliance.override_ended'),
  ('admin', 'compliance.override_started'),
  ('admin', 'compliance.send_blocked'),
  ('admin', 'consent.updated'),
  ('admin', 'earnings.updated'),
  ('admin', 'integration.mapping_verified'),
  ('admin', 'lead.duplicate_detected'),
  ('audit', 'activity.completed'),
  ('audit', 'activity.created'),
  ('audit', 'activity.overdue'),
  ('audit', 'admin.setting_changed'),
  ('audit', 'appointment.canceled'),
  ('audit', 'appointment.completed'),
  ('audit', 'appointment.no_showed'),
  ('audit', 'appointment.rescheduled'),
  ('audit', 'appointment.scheduled'),
  ('audit', 'appointment.starting_soon'),
  ('audit', 'automation.executed'),
  ('audit', 'calendar.sync_failed'),
  ('audit', 'call.completed'),
  ('audit', 'call.enriched'),
  ('audit', 'call.initiated'),
  ('audit', 'celebration.triggered'),
  ('audit', 'compliance.override_ended'),
  ('audit', 'compliance.override_started'),
  ('audit', 'compliance.send_blocked'),
  ('audit', 'consent.updated'),
  ('audit', 'contact.bad_number_flagged'),
  ('audit', 'contact.became_client'),
  ('audit', 'contact.created'),
  ('audit', 'contact.merged'),
  ('audit', 'contact.owner_changed'),
  ('audit', 'earnings.updated'),
  ('audit', 'integration.mapping_verified'),
  ('audit', 'lead.created'),
  ('audit', 'lead.duplicate_detected'),
  ('audit', 'lead.import_completed'),
  ('audit', 'lead.reposted'),
  ('audit', 'leaderboard.rank_changed'),
  ('audit', 'message.delivery_failed'),
  ('audit', 'message.received'),
  ('audit', 'message.sent'),
  ('audit', 'opportunity.created'),
  ('audit', 'opportunity.gate_blocked'),
  ('audit', 'opportunity.lost'),
  ('audit', 'opportunity.recycled'),
  ('audit', 'opportunity.reopened'),
  ('audit', 'opportunity.stage_changed'),
  ('audit', 'opportunity.value_changed'),
  ('audit', 'opportunity.went_cold'),
  ('audit', 'opportunity.won'),
  ('audit', 'pipeline.stage_config_changed'),
  ('audit', 'sequence.completed'),
  ('audit', 'sequence.enrolled'),
  ('audit', 'sequence.paused'),
  ('audit', 'user.deactivated'),
  ('automations', 'activity.completed'),
  ('automations', 'appointment.canceled'),
  ('automations', 'appointment.completed'),
  ('automations', 'appointment.no_showed'),
  ('automations', 'appointment.rescheduled'),
  ('automations', 'appointment.scheduled'),
  ('automations', 'call.completed'),
  ('automations', 'call.initiated'),
  ('automations', 'consent.updated'),
  ('automations', 'contact.became_client'),
  ('automations', 'lead.created'),
  ('automations', 'message.received'),
  ('automations', 'message.sent'),
  ('automations', 'opportunity.created'),
  ('automations', 'opportunity.lost'),
  ('automations', 'opportunity.recycled'),
  ('automations', 'opportunity.stage_changed'),
  ('automations', 'opportunity.went_cold'),
  ('automations', 'opportunity.won'),
  ('automations', 'pipeline.stage_config_changed'),
  ('automations', 'sequence.completed'),
  ('calendar', 'appointment.rescheduled'),
  ('calendar', 'appointment.scheduled'),
  ('calendar', 'user.deactivated'),
  ('celebration', 'leaderboard.rank_changed'),
  ('communications', 'compliance.override_ended'),
  ('communications', 'compliance.override_started'),
  ('communications', 'consent.updated'),
  ('communications', 'contact.bad_number_flagged'),
  ('communications', 'contact.merged'),
  ('communications', 'contact.owner_changed'),
  ('communications', 'integration.mapping_verified'),
  ('communications', 'lead.created'),
  ('communications', 'message.delivery_failed'),
  ('communications', 'message.received'),
  ('communications', 'opportunity.recycled'),
  ('communications', 'opportunity.stage_changed'),
  ('communications', 'opportunity.won'),
  ('communications', 'sequence.enrolled'),
  ('communications', 'sequence.paused'),
  ('communications', 'user.deactivated'),
  ('contacts', 'activity.completed'),
  ('contacts', 'appointment.completed'),
  ('contacts', 'appointment.no_showed'),
  ('contacts', 'appointment.scheduled'),
  ('contacts', 'call.completed'),
  ('contacts', 'call.enriched'),
  ('contacts', 'call.initiated'),
  ('contacts', 'compliance.send_blocked'),
  ('contacts', 'contact.merged'),
  ('contacts', 'lead.created'),
  ('contacts', 'lead.duplicate_detected'),
  ('contacts', 'lead.import_completed'),
  ('contacts', 'lead.reposted'),
  ('contacts', 'message.delivery_failed'),
  ('contacts', 'message.received'),
  ('contacts', 'message.sent'),
  ('contacts', 'opportunity.created'),
  ('contacts', 'opportunity.lost'),
  ('contacts', 'opportunity.recycled'),
  ('contacts', 'opportunity.stage_changed'),
  ('contacts', 'opportunity.won'),
  ('contacts', 'sequence.enrolled'),
  ('contacts', 'sequence.paused'),
  ('earnings', 'activity.completed'),
  ('earnings', 'appointment.completed'),
  ('earnings', 'call.completed'),
  ('earnings', 'contact.merged'),
  ('earnings', 'contact.owner_changed'),
  ('earnings', 'opportunity.reopened'),
  ('earnings', 'opportunity.value_changed'),
  ('earnings', 'opportunity.won'),
  ('earnings', 'pipeline.stage_config_changed'),
  ('earnings', 'user.deactivated'),
  ('in-app-toast', 'celebration.triggered'),
  ('kiosk', 'celebration.triggered'),
  ('kiosk', 'leaderboard.rank_changed'),
  ('leaderboard', 'celebration.triggered'),
  ('leaderboard', 'earnings.updated'),
  ('leaderboard', 'leaderboard.rank_changed'),
  ('my-day', 'activity.created'),
  ('my-day', 'activity.overdue'),
  ('my-day', 'appointment.starting_soon'),
  ('notifications', 'activity.created'),
  ('notifications', 'activity.overdue'),
  ('notifications', 'admin.setting_changed'),
  ('notifications', 'appointment.canceled'),
  ('notifications', 'appointment.no_showed'),
  ('notifications', 'appointment.rescheduled'),
  ('notifications', 'appointment.scheduled'),
  ('notifications', 'appointment.starting_soon'),
  ('notifications', 'automation.executed'),
  ('notifications', 'calendar.sync_failed'),
  ('notifications', 'call.completed'),
  ('notifications', 'compliance.override_ended'),
  ('notifications', 'compliance.override_started'),
  ('notifications', 'compliance.send_blocked'),
  ('notifications', 'consent.updated'),
  ('notifications', 'earnings.updated'),
  ('notifications', 'integration.mapping_verified'),
  ('notifications', 'lead.created'),
  ('notifications', 'lead.duplicate_detected'),
  ('notifications', 'lead.import_completed'),
  ('notifications', 'leaderboard.rank_changed'),
  ('notifications', 'message.delivery_failed'),
  ('notifications', 'message.received'),
  ('notifications', 'opportunity.lost'),
  ('notifications', 'opportunity.reopened'),
  ('notifications', 'opportunity.stage_changed'),
  ('notifications', 'opportunity.value_changed'),
  ('notifications', 'opportunity.went_cold'),
  ('notifications', 'opportunity.won'),
  ('notifications', 'pipeline.stage_config_changed'),
  ('notifications', 'sequence.paused'),
  ('notifications', 'user.deactivated'),
  ('pipeline', 'activity.completed'),
  ('pipeline', 'activity.created'),
  ('pipeline', 'activity.overdue'),
  ('pipeline', 'appointment.canceled'),
  ('pipeline', 'appointment.completed'),
  ('pipeline', 'appointment.no_showed'),
  ('pipeline', 'appointment.rescheduled'),
  ('pipeline', 'appointment.scheduled'),
  ('pipeline', 'call.completed'),
  ('pipeline', 'call.enriched'),
  ('pipeline', 'call.initiated'),
  ('pipeline', 'consent.updated'),
  ('pipeline', 'contact.bad_number_flagged'),
  ('pipeline', 'contact.became_client'),
  ('pipeline', 'contact.merged'),
  ('pipeline', 'contact.owner_changed'),
  ('pipeline', 'lead.created'),
  ('pipeline', 'lead.import_completed'),
  ('pipeline', 'message.received'),
  ('pipeline', 'message.sent'),
  ('pipeline', 'opportunity.went_cold'),
  ('pipeline', 'pipeline.stage_config_changed'),
  ('pipeline', 'user.deactivated'),
  ('push', 'celebration.triggered'),
  ('reporting', 'activity.completed'),
  ('reporting', 'activity.created'),
  ('reporting', 'activity.overdue'),
  ('reporting', 'admin.setting_changed'),
  ('reporting', 'appointment.canceled'),
  ('reporting', 'appointment.completed'),
  ('reporting', 'appointment.no_showed'),
  ('reporting', 'appointment.rescheduled'),
  ('reporting', 'appointment.scheduled'),
  ('reporting', 'automation.executed'),
  ('reporting', 'call.completed'),
  ('reporting', 'call.enriched'),
  ('reporting', 'call.initiated'),
  ('reporting', 'celebration.triggered'),
  ('reporting', 'compliance.override_ended'),
  ('reporting', 'compliance.override_started'),
  ('reporting', 'compliance.send_blocked'),
  ('reporting', 'consent.updated'),
  ('reporting', 'contact.bad_number_flagged'),
  ('reporting', 'contact.became_client'),
  ('reporting', 'contact.created'),
  ('reporting', 'contact.merged'),
  ('reporting', 'contact.owner_changed'),
  ('reporting', 'earnings.updated'),
  ('reporting', 'lead.created'),
  ('reporting', 'lead.duplicate_detected'),
  ('reporting', 'lead.import_completed'),
  ('reporting', 'lead.reposted'),
  ('reporting', 'leaderboard.rank_changed'),
  ('reporting', 'message.delivery_failed'),
  ('reporting', 'message.received'),
  ('reporting', 'message.sent'),
  ('reporting', 'opportunity.created'),
  ('reporting', 'opportunity.gate_blocked'),
  ('reporting', 'opportunity.lost'),
  ('reporting', 'opportunity.recycled'),
  ('reporting', 'opportunity.reopened'),
  ('reporting', 'opportunity.stage_changed'),
  ('reporting', 'opportunity.value_changed'),
  ('reporting', 'opportunity.went_cold'),
  ('reporting', 'opportunity.won'),
  ('reporting', 'pipeline.stage_config_changed'),
  ('reporting', 'sequence.completed'),
  ('reporting', 'sequence.enrolled'),
  ('reporting', 'sequence.paused'),
  ('reporting', 'user.deactivated'),
  ('search', 'contact.created'),
  ('seller-dashboard', 'earnings.updated')
ON CONFLICT DO NOTHING;
--> statement-breakpoint

SELECT security.harden();
